### ISSUE TITLE
Demo bundle 404

### ISSUE THREAD

**Issue by DJTB** [jxnblk/react-x-ray#7]
bundle.js is 404ing on the demo site for me.

**Comment by jtrein** [comment]
Yeah, come on, man! ;-) This ruined my week. Cool project, though, seriously. And would love to have the demo fixed. Is it something we can PR?

**Comment by muhajirdev** [comment]
yeah, any fix @jxnblk ?

**Comment by jxnblk** [comment]
Sorry for the delay. Should be fixed now
